### ISSUE TITLE
Unable to create MR, fatal: bad revision with git rev-list

### ISSUE THREAD

**Issue by kostajh** [yaoyuannnn/gitlab-gerrit-review#45]
I'm trying to create a MR with gerritlab. I have configured the target branch to be `main`. I get this error when I run `git lab`:

```
Traceback (most recent call last):
  File "/Users/kostajh/src/gerritlab/venv/bin/git-lab", line 8, in <module>
    sys.exit(main())
  File "/Users/kostajh/src/gerritlab/venv/lib/python3.9/site-packages/gerritlab/main.py", line 337, in main
    create_merge_requests(repo, remote, local_branch)
  File "/Users/kostajh/src/gerritlab/venv/lib/python3.9/site-packages/gerritlab/main.py", line 139, in create_merge_requests
    commits = list(
  File "/Users/kostajh/src/gerritlab/venv/lib/python3.9/site-packages/git/objects/commit.py", line 482, in _iter_from_process_or_stream
    finalize_process(proc_or_stream)
  File "/Users/kostajh/src/gerritlab/venv/lib/python3.9/site-packages/git/util.py", line 437, in finalize_process
    proc.wait(**kwargs)
  File "/Users/kostajh/src/gerritlab/venv/lib/python3.9/site-packages/git/cmd.py", line 602, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-list origin/main..gerritlab --
  stderr: 'fatal: bad revision 'origin/main..gerritlab'
```

And indeed, `git rev-list origin/main..gerritlab --` returns:`fatal: bad revision 'origin/main..gerritlab'` while ` git rev-list main..gerritlab` returns `bd6e6841775e04432bb3539f9f8daa870f0398ad`

Not sure what I am doing wrong. Suggestions welcome :)

**Comment by dancysoft** [comment]
Hi Kosta.  What does `ls -Fsa .git/refs/remotes/origin/` show?

**Comment by kostajh** [comment]
> ls -Fsa .git/refs/remotes/origin/

```
ls -Fsa .git/refs/remotes/origin/
total 8
0 ./    0 ../   8 HEAD
```

**Comment by dancysoft** [comment]
Thanks. Next, what are the contents of `.git/config` ?

**Comment by kostajh** [comment]
I didn't see any obvious issues between `.git/config` in my repo and `.git/config` in a freshly-cloned repo for this project.

I did `git remote remove origin` and re-added origin, and everything works now. 🤷
